server:
  port: 8082

spring:
  application:
    name: advanced-producer

  # Local Kafka Cluster
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      security.protocol: PLAINTEXT

      # Local Schema Registry
      schema.registry.url: http://127.0.0.1:8085

    # Kafka Producer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        enable.idempotence: true

# Kafka topic
kafka:
  push:
    topic: push.largest_picture.sol.avro

logging:
  level:
    org:
      springframework:
        kafka: TRACE
