spring:
  application:
    name: basic-producer
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: pagamento.request.topic.v1  # O nome do tópico pode ser configurado diretamente aqui
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 9090

topicos:
  pagamento:
    request:
      topic: "pagamento.request.topic.v1"  # Este valor agora é utilizado corretamente na classe `PagamentoRequestProducer`
